/*
 * Bundle Profile API
 * MC product bundle profile
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Digital_Enablement_Team_3@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.bundle_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Account
 */
public class AccountTest {
    private final Account model = new Account();

    /**
     * Model tests for Account
     */
    @Test
    public void testAccount() {
        // TODO: test Account
    }

    /**
     * Test the property 'ica'
     */
    @Test
    public void icaTest() {
        // TODO: test ica
    }

    /**
     * Test the property 'pan'
     */
    @Test
    public void panTest() {
        // TODO: test pan
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'productType'
     */
    @Test
    public void productTypeTest() {
        // TODO: test productType
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'par'
     */
    @Test
    public void parTest() {
        // TODO: test par
    }

    /**
     * Test the property 'nameOnCard'
     */
    @Test
    public void nameOnCardTest() {
        // TODO: test nameOnCard
    }

    /**
     * Test the property 'cardExpiryDate'
     */
    @Test
    public void cardExpiryDateTest() {
        // TODO: test cardExpiryDate
    }

    /**
     * Test the property 'cvcCode'
     */
    @Test
    public void cvcCodeTest() {
        // TODO: test cvcCode
    }

    /**
     * Test the property 'brand'
     */
    @Test
    public void brandTest() {
        // TODO: test brand
    }

    /**
     * Test the property 'productLine'
     */
    @Test
    public void productLineTest() {
        // TODO: test productLine
    }

    /**
     * Test the property 'primary'
     */
    @Test
    public void primaryTest() {
        // TODO: test primary
    }

    /**
     * Test the property 'cardAlias'
     */
    @Test
    public void cardAliasTest() {
        // TODO: test cardAlias
    }

    /**
     * Test the property 'last4Pan'
     */
    @Test
    public void last4PanTest() {
        // TODO: test last4Pan
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

}
