/*
 * Bundle Profile API
 * MC product bundle profile
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Digital_Enablement_Team_3@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.bundle_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Consent
 */
public class ConsentTest {
    private final Consent model = new Consent();

    /**
     * Model tests for Consent
     */
    @Test
    public void testConsent() {
        // TODO: test Consent
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'useCategoryCode'
     */
    @Test
    public void useCategoryCodeTest() {
        // TODO: test useCategoryCode
    }

    /**
     * Test the property 'serviceCode'
     */
    @Test
    public void serviceCodeTest() {
        // TODO: test serviceCode
    }

    /**
     * Test the property 'serviceFunctionCode'
     */
    @Test
    public void serviceFunctionCodeTest() {
        // TODO: test serviceFunctionCode
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'consentedDate'
     */
    @Test
    public void consentedDateTest() {
        // TODO: test consentedDate
    }

    /**
     * Test the property 'consentType'
     */
    @Test
    public void consentTypeTest() {
        // TODO: test consentType
    }

    /**
     * Test the property 'agreed'
     */
    @Test
    public void agreedTest() {
        // TODO: test agreed
    }

    /**
     * Test the property 'useCategoryValue'
     */
    @Test
    public void useCategoryValueTest() {
        // TODO: test useCategoryValue
    }

}
