/*
 * Bundle Profile API
 * MC product bundle profile
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Digital_Enablement_Team_3@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.bundle_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserReadAccountResponse
 */
public class UserReadAccountResponseTest {
    private final UserReadAccountResponse model = new UserReadAccountResponse();

    /**
     * Model tests for UserReadAccountResponse
     */
    @Test
    public void testUserReadAccountResponse() {
        // TODO: test UserReadAccountResponse
    }

    /**
     * Test the property 'last4Pan'
     */
    @Test
    public void last4PanTest() {
        // TODO: test last4Pan
    }

}
