/*
 * Bundle Profile API
 * MC product bundle profile
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Digital_Enablement_Team_3@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.bundle_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Address
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T15:18:38.136+05:30[Asia/Calcutta]")
public class Address {
  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_FORMATTED = "formatted";
  @SerializedName(SERIALIZED_NAME_FORMATTED)
  private String formatted;

  public static final String SERIALIZED_NAME_LOCALITY = "locality";
  @SerializedName(SERIALIZED_NAME_LOCALITY)
  private String locality;

  public static final String SERIALIZED_NAME_OPERATION = "operation";
  @SerializedName(SERIALIZED_NAME_OPERATION)
  private String operation;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postalCode";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  private String postalCode;

  public static final String SERIALIZED_NAME_PRIMARY = "primary";
  @SerializedName(SERIALIZED_NAME_PRIMARY)
  private Boolean primary;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  private String region;

  public static final String SERIALIZED_NAME_STREET_ADDRESS = "streetAddress";
  @SerializedName(SERIALIZED_NAME_STREET_ADDRESS)
  private String streetAddress;

  public static final String SERIALIZED_NAME_STREET_ADDRESS2 = "streetAddress2";
  @SerializedName(SERIALIZED_NAME_STREET_ADDRESS2)
  private String streetAddress2;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public Address country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * ISO Format Alpha-2 Code for Country in UpperCase
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "US", value = "ISO Format Alpha-2 Code for Country in UpperCase")

  public String getCountry() {
    return country;
  }



  public void setCountry(String country) {
    this.country = country;
  }


  public Address formatted(String formatted) {
    
    this.formatted = formatted;
    return this;
  }

   /**
   * The full mailing address, formatted for display or use with a mailing label. This attribute may contain newlines.
   * @return formatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "99 Mason Street #999 Jersey City, NJ 07302", value = "The full mailing address, formatted for display or use with a mailing label. This attribute may contain newlines.")

  public String getFormatted() {
    return formatted;
  }



  public void setFormatted(String formatted) {
    this.formatted = formatted;
  }


  public Address locality(String locality) {
    
    this.locality = locality;
    return this;
  }

   /**
   * The city or locality component.
   * @return locality
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "city", value = "The city or locality component.")

  public String getLocality() {
    return locality;
  }



  public void setLocality(String locality) {
    this.locality = locality;
  }


  public Address operation(String operation) {
    
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOperation() {
    return operation;
  }



  public void setOperation(String operation) {
    this.operation = operation;
  }


  public Address postalCode(String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * The zip code or postal code component.
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "63366", value = "The zip code or postal code component.")

  public String getPostalCode() {
    return postalCode;
  }



  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public Address primary(Boolean primary) {
    
    this.primary = primary;
    return this;
  }

   /**
   * A Boolean value indicating the &#39;primary&#39; or preferred address. The primary attribute value &#39;true&#39; must appear no more than once.
   * @return primary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "A Boolean value indicating the 'primary' or preferred address. The primary attribute value 'true' must appear no more than once.")

  public Boolean getPrimary() {
    return primary;
  }



  public void setPrimary(Boolean primary) {
    this.primary = primary;
  }


  public Address region(String region) {
    
    this.region = region;
    return this;
  }

   /**
   * The state or region component.
   * @return region
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "NJ", value = "The state or region component.")

  public String getRegion() {
    return region;
  }



  public void setRegion(String region) {
    this.region = region;
  }


  public Address streetAddress(String streetAddress) {
    
    this.streetAddress = streetAddress;
    return this;
  }

   /**
   * Street address of residence (Line 1)
   * @return streetAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "123 Main St.", value = "Street address of residence (Line 1)")

  public String getStreetAddress() {
    return streetAddress;
  }



  public void setStreetAddress(String streetAddress) {
    this.streetAddress = streetAddress;
  }


  public Address streetAddress2(String streetAddress2) {
    
    this.streetAddress2 = streetAddress2;
    return this;
  }

   /**
   * Street address of residence (Line 2)
   * @return streetAddress2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Suite 20", value = "Street address of residence (Line 2)")

  public String getStreetAddress2() {
    return streetAddress2;
  }



  public void setStreetAddress2(String streetAddress2) {
    this.streetAddress2 = streetAddress2;
  }


  public Address type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * A label indicating the attribute&#39;s function, Accepted values include: [work, home, billing, shipping, other]
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "work", value = "A label indicating the attribute's function, Accepted values include: [work, home, billing, shipping, other]")

  public String getType() {
    return type;
  }



  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return Objects.equals(this.country, address.country) &&
        Objects.equals(this.formatted, address.formatted) &&
        Objects.equals(this.locality, address.locality) &&
        Objects.equals(this.operation, address.operation) &&
        Objects.equals(this.postalCode, address.postalCode) &&
        Objects.equals(this.primary, address.primary) &&
        Objects.equals(this.region, address.region) &&
        Objects.equals(this.streetAddress, address.streetAddress) &&
        Objects.equals(this.streetAddress2, address.streetAddress2) &&
        Objects.equals(this.type, address.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, formatted, locality, operation, postalCode, primary, region, streetAddress, streetAddress2, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    formatted: ").append(toIndentedString(formatted)).append("\n");
    sb.append("    locality: ").append(toIndentedString(locality)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    streetAddress: ").append(toIndentedString(streetAddress)).append("\n");
    sb.append("    streetAddress2: ").append(toIndentedString(streetAddress2)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

