/*
 * Bundle Profile API
 * MC product bundle profile
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Digital_Enablement_Team_3@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.bundle_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Email
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T15:18:38.136+05:30[Asia/Calcutta]")
public class Email {
  public static final String SERIALIZED_NAME_DISPLAY = "display";
  @SerializedName(SERIALIZED_NAME_DISPLAY)
  private String display;

  public static final String SERIALIZED_NAME_OPERATION = "operation";
  @SerializedName(SERIALIZED_NAME_OPERATION)
  private String operation;

  public static final String SERIALIZED_NAME_PRIMARY = "primary";
  @SerializedName(SERIALIZED_NAME_PRIMARY)
  private Boolean primary;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;


  public Email display(String display) {
    
    this.display = display;
    return this;
  }

   /**
   * User&#39;s primary email address just for the display purpose
   * @return display
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Primary email address of user", value = "User's primary email address just for the display purpose")

  public String getDisplay() {
    return display;
  }



  public void setDisplay(String display) {
    this.display = display;
  }


  public Email operation(String operation) {
    
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOperation() {
    return operation;
  }



  public void setOperation(String operation) {
    this.operation = operation;
  }


  public Email primary(Boolean primary) {
    
    this.primary = primary;
    return this;
  }

   /**
   * A Boolean value indicating the &#39;primary&#39; or preferred email, The primary attribute value &#39;true&#39; must appear no more than once.
   * @return primary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "A Boolean value indicating the 'primary' or preferred email, The primary attribute value 'true' must appear no more than once.")

  public Boolean getPrimary() {
    return primary;
  }



  public void setPrimary(Boolean primary) {
    this.primary = primary;
  }


  public Email type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * A label indicating the attribute&#39;s function, Accepted values include: [work, home, other]
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "home", value = "A label indicating the attribute's function, Accepted values include: [work, home, other]")

  public String getType() {
    return type;
  }



  public void setType(String type) {
    this.type = type;
  }


  public Email value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Email address of the user e.g. &#39;bjensen@example.com&#39;
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "sally.cardholder@mail.com", value = "Email address of the user e.g. 'bjensen@example.com'")

  public String getValue() {
    return value;
  }



  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Email email = (Email) o;
    return Objects.equals(this.display, email.display) &&
        Objects.equals(this.operation, email.operation) &&
        Objects.equals(this.primary, email.primary) &&
        Objects.equals(this.type, email.type) &&
        Objects.equals(this.value, email.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(display, operation, primary, type, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Email {\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

