/*
 * Bundle Profile API
 * MC product bundle profile
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Digital_Enablement_Team_3@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.bundle_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PhoneNumber
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T15:18:38.136+05:30[Asia/Calcutta]")
public class PhoneNumber {
  public static final String SERIALIZED_NAME_DISPLAY = "display";
  @SerializedName(SERIALIZED_NAME_DISPLAY)
  private String display;

  public static final String SERIALIZED_NAME_OPERATION = "operation";
  @SerializedName(SERIALIZED_NAME_OPERATION)
  private String operation;

  public static final String SERIALIZED_NAME_PRIMARY = "primary";
  @SerializedName(SERIALIZED_NAME_PRIMARY)
  private Boolean primary;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;


  public PhoneNumber display(String display) {
    
    this.display = display;
    return this;
  }

   /**
   * Display for user&#39;s given phonenumber
   * @return display
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Display for user's given phonenumber")

  public String getDisplay() {
    return display;
  }



  public void setDisplay(String display) {
    this.display = display;
  }


  public PhoneNumber operation(String operation) {
    
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOperation() {
    return operation;
  }



  public void setOperation(String operation) {
    this.operation = operation;
  }


  public PhoneNumber primary(Boolean primary) {
    
    this.primary = primary;
    return this;
  }

   /**
   * Identifies if the phone number is primary (true/false)
   * @return primary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Identifies if the phone number is primary (true/false)")

  public Boolean getPrimary() {
    return primary;
  }



  public void setPrimary(Boolean primary) {
    this.primary = primary;
  }


  public PhoneNumber type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Phone number type. Accepted values include: [work, home, mobile, fax, pager, other]
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "fax", value = "Phone number type. Accepted values include: [work, home, mobile, fax, pager, other]")

  public String getType() {
    return type;
  }



  public void setType(String type) {
    this.type = type;
  }


  public PhoneNumber value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Phone number of the User (e.g. +1-201-555-0123)
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "+1-201-555-0123", value = "Phone number of the User (e.g. +1-201-555-0123)")

  public String getValue() {
    return value;
  }



  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneNumber phoneNumber = (PhoneNumber) o;
    return Objects.equals(this.display, phoneNumber.display) &&
        Objects.equals(this.operation, phoneNumber.operation) &&
        Objects.equals(this.primary, phoneNumber.primary) &&
        Objects.equals(this.type, phoneNumber.type) &&
        Objects.equals(this.value, phoneNumber.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(display, operation, primary, type, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneNumber {\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

