/*
 * Bundle Profile API
 * MC product bundle profile
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Digital_Enablement_Team_3@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.bundle_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.developer.bundle_client.model.Account;
import com.mastercard.developer.bundle_client.model.Consent;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UserProduct
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T15:18:38.136+05:30[Asia/Calcutta]")
public class UserProduct {
  public static final String SERIALIZED_NAME_PRODUCT = "product";
  @SerializedName(SERIALIZED_NAME_PRODUCT)
  private String product;

  public static final String SERIALIZED_NAME_CONSENTS = "consents";
  @SerializedName(SERIALIZED_NAME_CONSENTS)
  private List<Consent> consents = null;

  public static final String SERIALIZED_NAME_ACCOUNTS = "accounts";
  @SerializedName(SERIALIZED_NAME_ACCOUNTS)
  private List<Account> accounts = null;

  public static final String SERIALIZED_NAME_OBJECT = "object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  private Object _object;


  public UserProduct product(String product) {
    
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @ApiModelProperty(example = "benefits", required = true, value = "")

  public String getProduct() {
    return product;
  }



  public void setProduct(String product) {
    this.product = product;
  }


  public UserProduct consents(List<Consent> consents) {
    
    this.consents = consents;
    return this;
  }

  public UserProduct addConsentsItem(Consent consentsItem) {
    if (this.consents == null) {
      this.consents = new ArrayList<>();
    }
    this.consents.add(consentsItem);
    return this;
  }

   /**
   * Get consents
   * @return consents
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Consent> getConsents() {
    return consents;
  }



  public void setConsents(List<Consent> consents) {
    this.consents = consents;
  }


  public UserProduct accounts(List<Account> accounts) {
    
    this.accounts = accounts;
    return this;
  }

  public UserProduct addAccountsItem(Account accountsItem) {
    if (this.accounts == null) {
      this.accounts = new ArrayList<>();
    }
    this.accounts.add(accountsItem);
    return this;
  }

   /**
   * Get accounts
   * @return accounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Account> getAccounts() {
    return accounts;
  }



  public void setAccounts(List<Account> accounts) {
    this.accounts = accounts;
  }


  public UserProduct _object(Object _object) {
    
    this._object = _object;
    return this;
  }

   /**
   * Extended user object (with localized metadata) for the given product of the requested user.  See Developer Portal (https://developer.mastercard.com/documentation/product-bundle-registration/v1) for additional documentation of the product-specific fields.
   * @return _object
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"username\":\"boingoid123\",\"password\":\"boingopwd\"}", value = "Extended user object (with localized metadata) for the given product of the requested user.  See Developer Portal (https://developer.mastercard.com/documentation/product-bundle-registration/v1) for additional documentation of the product-specific fields.")

  public Object getObject() {
    return _object;
  }



  public void setObject(Object _object) {
    this._object = _object;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserProduct userProduct = (UserProduct) o;
    return Objects.equals(this.product, userProduct.product) &&
        Objects.equals(this.consents, userProduct.consents) &&
        Objects.equals(this.accounts, userProduct.accounts) &&
        Objects.equals(this._object, userProduct._object);
  }

  @Override
  public int hashCode() {
    return Objects.hash(product, consents, accounts, _object);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserProduct {\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    consents: ").append(toIndentedString(consents)).append("\n");
    sb.append("    accounts: ").append(toIndentedString(accounts)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

